version: '3.8'

services:
  tcg-api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - PORT=8080
    networks:
      - tcg-network

networks:
  tcg-network:
    driver: bridge
